name: deploy-with-gh-pages
on:
  push:
    branches:
      - action-demo
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm ci
          npm run prod

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: wwwroot
          clean: true
          token: ${{ secrets.ACCESS_TOKEN }}
